### ISSUE TITLE
tensorflow-gpu on Tesla V100

### ISSUE THREAD

**Issue by dacron** [ContinuumIO/anaconda-issues#10620]
### Actual Behavior
tensorflow-gpu is unable to attach to a GPU.

```
(tensorflow) $ python -c "import tensorflow as tf; hello = tf.constant('Hello, TensorFlow'); sess = tf.Session(); print(sess.run(hello));"
2019-02-12 15:45:36.853173: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2019-02-12 15:45:36.870515: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2019-02-12 15:45:36.870567: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: [removed]
2019-02-12 15:45:36.870577: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: [removed]
2019-02-12 15:45:36.870628: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 410.79.0
2019-02-12 15:45:36.870669: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 410.79.0
2019-02-12 15:45:36.870678: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 410.79.0
b'Hello, TensorFlow'
```

### Expected Behavior
tensorflow-gpu should be able to attach to GPU devices

### Steps to Reproduce

- Install Miniconda3 4.5.12
- `conda create -n tensorflow tensorflow-gpu`
- `source activate tensorflow`
- `python -c "import tensorflow as tf; hello = tf.constant('Hello, TensorFlow'); sess = tf.Session(); print(sess.run(hello));"`

##### Anaconda or Miniconda version:
Miniconda3 4.5.12

##### Operating System:
RHEL 7.6 Server - fully patched.

##### `conda info`
```
    active environment : tensorflow
    active env location : /home/adacre/.conda/envs/tensorflow
            shell level : 1
       user config file : /home/adacre/.condarc
 populated config files :
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /soft/miniconda3/4.5.12  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /soft/miniconda3/4.5.12/pkgs
                          /home/adacre/.conda/pkgs
       envs directories : /home/adacre/.conda/envs
                          /soft/miniconda3/4.5.12/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/3.10.0-957.5.1.el7.x86_64 rhel/7.6 glibc/2.17
                UID:GID : 40445:45575
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`
```
# packages in environment at /home/adacre/.conda/envs/tensorflow:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu    defaults
absl-py                   0.7.0                    py36_0    defaults
astor                     0.7.1                    py36_0    defaults
blas                      1.0                         mkl    defaults
c-ares                    1.15.0               h7b6447c_1    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2018.11.29               py36_0    defaults
cudatoolkit               9.2                           0    defaults
cudnn                     7.3.1                 cuda9.2_0    defaults
cupti                     9.2.148                       0    defaults
gast                      0.2.2                    py36_0    defaults
grpcio                    1.16.1           py36hf8bcb03_1    defaults
h5py                      2.9.0            py36h7918eee_0    defaults
hdf5                      1.10.4               hb1b8bf9_0    defaults
intel-openmp              2019.1                      144    defaults
keras-applications        1.0.6                    py36_0    defaults
keras-preprocessing       1.0.5                    py36_0    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libprotobuf               3.6.1                hd408876_0    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
markdown                  3.0.1                    py36_0    defaults
mkl                       2019.1                      144    defaults
mkl_fft                   1.0.10           py36ha843d7b_0    defaults
mkl_random                1.0.2            py36hd81dba3_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
numpy                     1.15.4           py36h7e9f1db_0    defaults
numpy-base                1.15.4           py36hde5b4d6_0    defaults
openssl                   1.1.1a               h7b6447c_0    defaults
pip                       19.0.1                   py36_0    defaults
protobuf                  3.6.1            py36he6710b0_0    defaults
python                    3.6.8                h0371630_0    defaults
readline                  7.0                  h7b6447c_5    defaults
scipy                     1.2.0            py36h7c811a0_0    defaults
setuptools                40.7.3                   py36_0    defaults
six                       1.12.0                   py36_0    defaults
sqlite                    3.26.0               h7b6447c_0    defaults
tensorboard               1.12.2           py36he6710b0_0    defaults
tensorflow                1.12.0          gpu_py36he74679b_0    defaults
tensorflow-base           1.12.0          gpu_py36had579c0_0    defaults
tensorflow-gpu            1.12.0               h0d30ee6_0    defaults
termcolor                 1.1.0                    py36_1    defaults
tk                        8.6.8                hbc83047_0    defaults
werkzeug                  0.14.1                   py36_0    defaults
wheel                     0.32.3                   py36_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```
#### GPU/Driver Informatoin
```
(tensorflow) [adacre@[removed] ~]$ nvidia-smi
Tue Feb 12 15:54:41 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:62:00.0 Off |                    0 |
| N/A   34C    P0    41W / 300W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
| N/A   36C    P0    42W / 300W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by HitLyn** [comment]
same error

**Comment by jjhelmus** [comment]
I was not able to replicate this issue on a system with a V100, although the setup was different.  Installing tensorflow-gpu and cudatoolkit=9.0 Tensorflow ran without issue and was able to use the GPU.  

This setup was a different from the one @dacron, the CUDA driver was older (384.145) and therefore an older cudatoolkit was used.  Can you share any of the information from the `retrieving CUDA diagnostic information for host: [removed]` line which might help debug this issue.

Additionally conda packages for tensorflow 1.13.1 will be available soon which will directly support CUDA 10.0, perhaps those will solve this issue.

**Comment by dacron** [comment]
Super odd. I've just created the environment again and it seems to work correctly. The difference between the two environments is below for extra history, but I think it is safe to resolve this issue.

```diff
--- broken      2019-03-05 13:19:53.741914440 +0000
+++ working     2019-03-05 13:20:03.673131447 +0000
@@ -26,15 +26,15 @@
 mkl_fft                   1.0.10           py36ha843d7b_0    defaults
 mkl_random                1.0.2            py36hd81dba3_0    defaults
 ncurses                   6.1                  he6710b0_1    defaults
-numpy                     1.15.4           py36h7e9f1db_0    defaults
-numpy-base                1.15.4           py36hde5b4d6_0    defaults
-openssl                   1.1.1a               h7b6447c_0    defaults
-pip                       19.0.1                   py36_0    defaults
+numpy                     1.16.2           py36h7e9f1db_0    defaults
+numpy-base                1.16.2           py36hde5b4d6_0    defaults
+openssl                   1.1.1b               h7b6447c_0    defaults
+pip                       19.0.3                   py36_0    defaults
 protobuf                  3.6.1            py36he6710b0_0    defaults
 python                    3.6.8                h0371630_0    defaults
 readline                  7.0                  h7b6447c_5    defaults
-scipy                     1.2.0            py36h7c811a0_0    defaults
-setuptools                40.7.3                   py36_0    defaults
+scipy                     1.2.1            py36h7c811a0_0    defaults
+setuptools                40.8.0                   py36_0    defaults
 six                       1.12.0                   py36_0    defaults
 sqlite                    3.26.0               h7b6447c_0    defaults
 tensorboard               1.12.2           py36he6710b0_0    defaults
@@ -44,6 +44,6 @@
 termcolor                 1.1.0                    py36_1    defaults
 tk                        8.6.8                hbc83047_0    defaults
 werkzeug                  0.14.1                   py36_0    defaults
-wheel                     0.32.3                   py36_0    defaults
+wheel                     0.33.1                   py36_0    defaults
 xz                        5.2.4                h14c3975_4    defaults
 zlib                      1.2.11               h7b6447c_3    defaults
```

**Comment by jjhelmus** [comment]
@dacron Glad to hear the issue resolved itself.  I do not see anything obvious in the environment different that would cause this change.
