### ISSUE TITLE
install tensorflow error : ImportError: libcublas.so.10.0

### ISSUE THREAD

**Issue by nobsessive** [ContinuumIO/anaconda-issues#11805]
I'm trying to install tensorflow with conda's "one-line" feature, error occurs when I run "import tensorflow as tf". Tensorflow-gpu seems trying to find another cudatoolkit pre-installed on the host.

### Actual Behavior

Traceback (most recent call last):
  File "/home/amaa/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/amaa/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/amaa/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/amaa/anaconda3/envs/tf_gpu/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/amaa/anaconda3/envs/tf_gpu/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amaa/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/amaa/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/amaa/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/amaa/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/amaa/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/amaa/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/amaa/anaconda3/envs/tf_gpu/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/amaa/anaconda3/envs/tf_gpu/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

### Expected Behavior

"import tensorflow as tf" doesn't produce anything

### Steps to Reproduce

conda create --name tf_gpu tensorflow-gpu=1.3.0
conda activate tf_gpu
python
import tensorflow as tf

##### Operating System:
Kernel: 4.15.0-99-generic x86_64 bits: 64 Desktop: Gnome 3.28.3
Distro: Ubuntu 18.04.1 LTS

##### `conda info`

<details>

````
     active environment : tf_gpu
    active env location : /home/amaa/anaconda3/envs/tf_gpu
            shell level : 1
       user config file : /home/amaa/.condarc
 populated config files : 
          conda version : 4.6.14
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : /home/amaa/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/amaa/anaconda3/pkgs
                          /home/amaa/.conda/pkgs
       envs directories : /home/amaa/anaconda3/envs
                          /home/amaa/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.1 Linux/4.15.0-99-generic ubuntu/18.04.1 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
````
</details>

##### `conda list --show-channel-urls`

<details>

````
# packages in environment at /home/amaa/anaconda3/envs/tf_gpu:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
backports                 1.0                        py_2    defaults
backports.weakref         1.0rc1                   py36_0    defaults
blas                      1.0                         mkl    defaults
bleach                    1.5.0                    py36_0    defaults
ca-certificates           2020.1.1                      0    defaults
certifi                   2020.4.5.1               py36_0    defaults
cudatoolkit               8.0                           3    defaults
cudnn                     6.0.21                cuda8.0_0    defaults
html5lib                  0.9999999                py36_0    defaults
intel-openmp              2020.1                      217    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.3                  he6710b0_1    defaults
libgcc                    7.2.0                h69d50b8_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libprotobuf               3.11.4               hd408876_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
markdown                  3.1.1                    py36_0    defaults
mkl                       2020.1                      217    defaults
mkl-service               2.3.0            py36he904b0f_0    defaults
mkl_fft                   1.0.15           py36ha843d7b_0    defaults
mkl_random                1.1.0            py36hd6b4f25_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
numpy                     1.18.1           py36h4f9e942_0    defaults
numpy-base                1.18.1           py36hde5b4d6_1    defaults
openssl                   1.1.1g               h7b6447c_0    defaults
pip                       20.0.2                   py36_3    defaults
protobuf                  3.11.4           py36he6710b0_0    defaults
python                    3.6.10               h7579374_2    defaults
readline                  8.0                  h7b6447c_0    defaults
setuptools                46.2.0                   py36_0    defaults
six                       1.14.0                   py36_0    defaults
sqlite                    3.31.1               h62c20be_1    defaults
tensorflow-gpu            1.3.0                         0    defaults
tensorflow-gpu-base       1.3.0           py36cuda8.0cudnn6.0_1    defaults
tensorflow-tensorboard    1.5.1            py36hf484d3e_1    defaults
tk                        8.6.8                hbc83047_0    defaults
werkzeug                  1.0.1                      py_0    defaults
wheel                     0.34.2                   py36_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
````
</details>

##### which nvcc (under tf_gpu)
<details>

````
/home/amaa/bin/nvcc
````
</details>

##### nvcc -V (under tf_gpu)
<details>

````
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
````
</details>

##### sys.path

<details>
['', '/home/amaa/anaconda3/envs/tf_gpu/lib/python36.zip', '/home/amaa/anaconda3/envs/tf_gpu/lib/python3.6', '/home/amaa/anaconda3/envs/tf_gpu/lib/python3.6/lib-dynload', '/home/amaa/.local/lib/python3.6/site-packages', '/home/amaa/anaconda3/envs/tf_gpu/lib/python3.6/site-packages']

````
</details>

**Comment by jjhelmus** [comment]
Tensorflow is being imported from your user site directory (/home/amaa/.local/lib/python3.6/site-packages) not the site-packages directory managed by conda (/home/amaa/anaconda3/envs/tf_gpu/lib/python3.6/site-packages).

Starting python with the `-s` flag with disable this directory although you may want consider removing that directory completely as there may be other things installer there that will cause conflicts.

**Comment by nobsessive** [comment]
> Tensorflow is being imported from your user site directory (/home/amaa/.local/lib/python3.6/site-packages) not the site-packages directory managed by conda (/home/amaa/anaconda3/envs/tf_gpu/lib/python3.6/site-packages).
> 
> Starting python with the `-s` flag with disable this directory although you may want consider removing that directory completely as there may be other things installer there that will cause conflicts.

Thank you! Issue resolved. 
May I ask a further question? Why is it a copy of python packages installed in ~/.local? It seems to me that conda put them there and added the path to sys.path even when I activate a specific env.

**Comment by jjhelmus** [comment]
> Why is it a copy of python packages installed in ~/.local?

Conda does not put packages into .local.  Running `pip install` might depending on the option that are passed and entries in various configuration files.  

The python shipped with conda adds this path to sys.path because that is the standard in Python. Changing this default would be confusing to many users, although keeping the default is also confusing to a different set of users :smile:.
